services:
  - type: web
    name: github-repo-tracker
    env: python
    buildCommand: "pip install -r requirements.txt && cd backend/frontend/admin-dashboard && npm install && npm run build && cd ../../../backend && python manage.py collectstatic --noinput"
    startCommand: "cd backend && python manage.py migrate && echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin123')\" | python manage.py shell && gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
